// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const closeOpenIncidentForMonitor = `-- name: CloseOpenIncidentForMonitor :many
UPDATE incidents
SET
    status = 'closed',
    closed_at = now()
WHERE monitor_id = $1
  AND status = 'open'
RETURNING id, monitor_id, status, opened_at, closed_at
`

func (q *Queries) CloseOpenIncidentForMonitor(ctx context.Context, monitorID uuid.UUID) ([]Incident, error) {
	rows, err := q.db.Query(ctx, closeOpenIncidentForMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOrGetOpenIncident = `-- name: CreateOrGetOpenIncident :one
INSERT INTO incidents (
    monitor_id
) VALUES (
    $1
)
ON CONFLICT (monitor_id) WHERE status = 'open'
DO UPDATE SET status = incidents.status
RETURNING id, monitor_id, status, opened_at, closed_at
`

// Intentionally uses a no-op UPDATE so concurrent callers can return the open incident.
func (q *Queries) CreateOrGetOpenIncident(ctx context.Context, monitorID uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, createOrGetOpenIncident, monitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOpenIncident = `-- name: GetOpenIncident :one
SELECT id, monitor_id, status, opened_at, closed_at
FROM incidents
WHERE monitor_id = $1
  AND status = 'open'
`

func (q *Queries) GetOpenIncident(ctx context.Context, monitorID uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getOpenIncident, monitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
	)
	return i, err
}
