// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckResult struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	MonitorID  uuid.UUID   `db:"monitor_id" json:"monitor_id"`
	Success    bool        `db:"success" json:"success"`
	StatusCode pgtype.Int4 `db:"status_code" json:"status_code"`
	LatencyMs  pgtype.Int8 `db:"latency_ms" json:"latency_ms"`
	Error      pgtype.Text `db:"error" json:"error"`
	CheckedAt  time.Time   `db:"checked_at" json:"checked_at"`
}

type Incident struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	MonitorID uuid.UUID          `db:"monitor_id" json:"monitor_id"`
	Status    string             `db:"status" json:"status"`
	OpenedAt  time.Time          `db:"opened_at" json:"opened_at"`
	ClosedAt  pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
}

type Monitor struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Url          string    `db:"url" json:"url"`
	IntervalSecs int32     `db:"interval_secs" json:"interval_secs"`
	TimeoutSecs  int32     `db:"timeout_secs" json:"timeout_secs"`
	Enabled      bool      `db:"enabled" json:"enabled"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}
