// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    name,
    url,
    interval_secs,
    timeout_secs,
    enabled
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, url, interval_secs, timeout_secs, enabled, created_at, updated_at
`

type CreateMonitorParams struct {
	Name         string `db:"name" json:"name"`
	Url          string `db:"url" json:"url"`
	IntervalSecs int32  `db:"interval_secs" json:"interval_secs"`
	TimeoutSecs  int32  `db:"timeout_secs" json:"timeout_secs"`
	Enabled      bool   `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.Name,
		arg.Url,
		arg.IntervalSecs,
		arg.TimeoutSecs,
		arg.Enabled,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IntervalSecs,
		&i.TimeoutSecs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonitor = `-- name: GetMonitor :one
SELECT id, name, url, interval_secs, timeout_secs, enabled, created_at, updated_at
FROM monitors
WHERE id = $1
`

func (q *Queries) GetMonitor(ctx context.Context, id uuid.UUID) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitor, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IntervalSecs,
		&i.TimeoutSecs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, name, url, interval_secs, timeout_secs, enabled, created_at, updated_at
FROM monitors
ORDER BY created_at DESC
`

func (q *Queries) ListMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.IntervalSecs,
			&i.TimeoutSecs,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
